// <auto-generated />
using Microsoft.AspNetCore.Components;
using Radzen;

namespace SGC_Database_Backup.Components.Layout
{
    public partial class MainLayout
    {
        [Inject]
        public DialogService DialogService { get; set; }


        bool sidebarExpanded = true;
    }
}
