// <auto-generated />
using Microsoft.AspNetCore.Components;
using Radzen;
using SGC_Database_Backup.Entities;
using SGC_Database_Backup.Services.Users;

namespace SGC_Database_Backup.Components.Pages.Administration.Users
{
    public partial class UserManagement
    {
        [Inject]
        private IUserService UserService { get; set; }
        [Inject]
        private DialogService DialogService { get; set; }

        private IEnumerable<User> users = [];
        private bool isLoading = false;
        protected override async Task OnInitializedAsync()
        {
            await LoadUsers();
        }

    
        private async Task LoadUsers()
        {
            try
            {
                isLoading = true;
                users = await UserService.GetAllAsync();

            }
            finally
            {
                isLoading = false;
            }
        }

        private async Task EditUser(int userId)
        {
            await DialogService.OpenAsync<AddEditUser>("Editar usuario", new Dictionary<string, object?> { { "UserId", userId },
                                                                                                           { "LoadUsers", EventCallback.Factory.Create(this, LoadUsers)
                                                                                                         } });
        }

        private async Task AddUser()
        {
            await DialogService.OpenAsync<AddEditUser>("Agregar usuario", new Dictionary<string, object?> { 
                { "LoadUsers", EventCallback.Factory.Create(this, LoadUsers) }
            });
        }

        
    }
}
