// <auto-generated />
using Microsoft.AspNetCore.Components;
using SGC_Database_Backup.Entities;
using SGC_Database_Backup.Repositories;

namespace SGC_Database_Backup.Components.Pages.Connections
{
    public partial class ConnectionManager
    {
        [Inject]
        private IDatabaseOptionsRepository DatabaseOptionService { get; set; }

        private IEnumerable<DatabaseOptions> databaseOptions { get; set; }
        private bool isLoading = false;
        protected override async Task OnInitializedAsync()
        {
            await LoadConnections();

        }

        private async Task LoadConnections()
        {
            try
            {
                isLoading = true;
                databaseOptions = await DatabaseOptionService.GetAllAsync();
            }
            finally
            {
                isLoading = false;

            }
        }

        private void EditConnection(int connectionId) { }

        private void AddConnection() { }
    }
}
