// <auto-generated />
using Microsoft.AspNetCore.Components;
using SGC_Database_Backup.Entities;
using SGC_Database_Backup.Repositories;

namespace SGC_Database_Backup.Components.Pages.Connections
{
    public partial class ConnectionManager
    {
        [Inject]
        private IDatabaseOptionsRepository DatabaseOptionService { get; set; }

        private IEnumerable<DatabaseOptions> databaseOptions { get; set; }
        protected override async Task OnInitializedAsync()
        {
            databaseOptions = await DatabaseOptionService.GetAllAsync();
        }
    }
}
